language: php
php:
- 5.3
- 5.4
- 5.5
- 5.6
- 7.0
script: "make test"
notifications:
  hipchat:
    rooms:
      - secure: TKe7Thma4yzEl8FtDe2wOqRlXTEPJG17tD7Mz3q57OkGVNUnfsl//VqBLAi0vkV5Tm9iU6zadjU5TefWicqldi2NeiGJVpLvM8Ul5bVzWJ99f3EQMxC0sGZVaK5ld/3/nKDKj1TB5zoPVVov+igjEFa4gaEtWifSgR1ayv21Wew=
    template:
      - 'Build #%{build_number} (%{commit}) of %{repository_name}/%{branch} %{result} (%{duration}) %{build_url}'
