language: php
php:
- 5.3
- 5.4
- 5.5
- 5.6
- 7.0
script: "make test"
notifications:
  hipchat:
    rooms:
      secure: E2vTn0Zp+IVVK2E2RfzmsFk4mEB3JpM2GqzIaXpRhsBKPgA6N3eIy7jAv5CYmXC4qVjaz2D4rSAs8/2s8xboTJN7YU04Srg6ZURVY2weVgOkocy6ZB5Kqo4nsE3/bJZRBh98ZtIQgwDE8YVBFMa6wqdze1SAK6CgDk0a0cxNN1Y=
    template:
      - 'Build #%{build_number} (%{commit}) of %{repository_name}/%{branch} %{result} (%{duration}) %{build_url}'
